Repository hms-networks/IgnitionEwonConnector, pull requests merged in 2019-08, with the labels that each got.

#32 Ignition 7.9 Boolean write fix
  eWonConnector-gateway/src/main/java/org/imdc/ewon/SyncManager.java
Labels: bug, ignition7.9

#34 Remove unthrown exception in Ignition 8
  eWonConnector-gateway/src/main/java/org/imdc/ewon/SyncManager.java
Labels: bug, ignition8

#33 Update Ewon Branding Capitalization in 7.9
  CHANGELOG.md
  eWonConnector-build/pom.xml
  eWonConnector-gateway/pom.xml
  eWonConnector-gateway/src/main/java/org/imdc/ewon/GatewayHook.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/SyncManager.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/config/EwonConnectorSettings.java
  eWonConnector-gateway/src/main/resources/ewon_gateway.properties
  eWonConnector-gateway/src/main/resources/org/imdc/ewon/config/EwonConnectorSettings.properties
  pom.xml
  readme.md
  tools/MakeRelease.py
Labels: ignition7.9

#35 Improve Code Commenting
  eWonConnector-gateway/src/main/java/org/imdc/ewon/EwonConsts.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/EwonUtil.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/GatewayHook.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/SyncManager.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/comm/AuthInfo.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/comm/CommunicationManger.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/config/EwonConfigPage.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/config/EwonConnectorSettings.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/config/EwonSyncData.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/config/SyncMode.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/config/TagHistoryListEditorSource.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/config/TagHistorySourceEditor.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/data/DMResult.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/data/DataPoint.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/data/EwonData.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/data/EwonsData.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/data/GetDataResult.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/data/Tag.java
Labels: enhancement, ignition7.9

#36 Individual Ewon Realtime Support
  eWonConnector-gateway/src/main/java/org/imdc/ewon/SyncManager.java
Labels: enhancement, ignition8

#38 Ignition 7.9 Realtime Support
  eWonConnector-gateway/src/main/java/org/imdc/ewon/EwonConsts.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/SyncManager.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/comm/CommunicationManger.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/config/EwonConnectorSettings.java
  eWonConnector-gateway/src/main/java/org/imdc/ewon/data/TMResult.java
  eWonConnector-gateway/src/main/resources/org/imdc/ewon/config/EwonConnectorSettings.properties
Labels: enhancement, ignition7.9

#46 Readme Link fix
  readme.md
Labels: Documentation, ignition8

#47 Changed API Key to Developer ID in config
  eWonConnector-gateway/src/main/resources/org/imdc/ewon/config/EwonConnectorSettings.properties
  readme.md
Labels: ignition8

#50 Updated Features section of readme
  readme.md
Labels: Documentation, ignition8

#51 Updated Troubleshooting section of readme
  readme.md
Labels: Documentation

#52 Ignition 8 readme fixes
  readme.md
Labels: Documentation, ignition8

#53 Clarified password change in readme
  readme.md
Labels: ignition8

#57 Added upgrading section to readme
  readme.md
Labels: Documentation

#61 #56 Update Configuration Page 7.9
  eWonConnector-gateway/src/main/java/org/imdc/ewon/config/EwonConnectorSettings.java
  eWonConnector-gateway/src/main/resources/org/imdc/ewon/config/EwonConnectorSettings.properties
Labels: enhancement, ignition7.9

#62 #55 Add authentication message into Ignition 7.9
  eWonConnector-gateway/src/main/java/org/imdc/ewon/EwonUtil.java
Labels: enhancement, ignition7.9

#63 #59 Fix NullPointerException at startup with a fresh install
  eWonConnector-gateway/src/main/java/org/imdc/ewon/config/EwonConnectorSettings.java
Labels: bug, ignition7.9

#64 Ignition 7.9 54 update ignition 7.9 readme
  images/auth_error.JPG
  images/config_page.JPG
  images/data_management_page.JPG
  images/module_config_page.JPG
  images/module_install_link.JPG
  images/module_install_page.JPG
  images/tag_browser.JPG
  images/tag_config_page.JPG
  images/vpn_wizard.JPG
  readme.md
Labels: Documentation, enhancement, ignition7.9
