Repository hms-networks/IgnitionEwonConnector, pull requests merged in 2019-09, with the labels that each got.

#73 Mark Tags as Bad if Sync or Write Fails
  eWonConnector-gateway/src/main/java/com/hms_networks/SyncManager.java
Labels: enhancement, ignition7.9

#72 Mark Tags as Bad if Sync or Write Fails
  eWonConnector-gateway/src/main/java/com/hms_networks/SyncManager.java
Labels: enhancement, ignition8

#80 Adjusted spaceing in MakeRelease.py
  tools/MakeRelease.py
Labels: ignition8

#84 Ignition 7.9 release build update
  tools/MakeRelease.py
Labels: enhancement, ignition7.9

#85 Update logging call formatting to all same
  eWonConnector-gateway/src/main/java/com/hms_networks/EwonUtil.java
  eWonConnector-gateway/src/main/java/com/hms_networks/GatewayHook.java
  eWonConnector-gateway/src/main/java/com/hms_networks/SyncManager.java
Labels: ignition8

#89 Fixed signed modl name in MakeRelease.py
  tools/MakeRelease.py
Labels: bug, ignition8

#88 Fixed signed modl name in MakeRelease.py
  tools/MakeRelease.py
Labels: bug, ignition7.9

#90 Ignition 8 release updates
  tools/MakeRelease.py
Labels: ignition8

#91 Ignition 7.9 release update
  tools/MakeRelease.py
Labels: ignition7.9
